name: Deploy EC2

on:
  workflow_dispatch:

jobs:
  Terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Generate an ssh keypair
        run: ssh-keygen -t rsa -b 4096 -f ./terraform/data/ec2

      - name: Output private key
        run: cat ./terraform/data/ec2
