name: Deploy EC2

on:
  workflow_dispatch:

jobs:
  Generate-SSH-Keypair:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Make data dir
        run: mkdir ./terraform/data

      - name: Generate an ssh keypair
        run: ssh-keygen -t rsa -b 4096 -f ./terraform/data/ec2 -N ${{ secrets.SSH_KEY_PASSPHRASE  }}

      - name: Output private key
        run: cat ./terraform/data/ec2

      - name: Output public key
        run: cat ./terraform/data/ec2.pub
