name: Destroy EC2

on:
  workflow_dispatch:

jobs:
  Terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bootstrap
        run: |
          mkdir ./terraform/data \
          ls ./terraform \
          echo "" > ./terraform/data/ec2.pub

      - name: Create env vars
        run: |
          echo AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID  }}" >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY  }}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Terraform init
        id: init
        run: |
          terraform \
          -chdir=./terraform \
          init \
          -backend-config="bucket=${{ vars.BACKEND_CONFIG_BUCKET  }}" \
          -backend-config="key=${{ vars.BACKEND_CONFIG_KEY  }}" \
          -backend-config="region=${{ vars.BACKEND_CONFIG_REGION  }}" \
          -backend-config="dynamodb_table=${{ vars.BACKEND_CONFIG_DYNAMODB_TABLE  }}"

      - name: Teraform destroy
        id: destroy
        run: |
          terraform \
          -chdir=./terraform \
          destroy \
          --auto-approve
