name: Destroy EC2

on:
  workflow_dispatch:

jobs:
  Bootstrap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create data dir
        run: mkdir ./terraform/data \

      - name: Create empty .pub file
        run: echo "" > ./terraform/data/ec2.pub

      - uses: actions/upload-artifact@v4
        with:
          name: ec2.pub
          path: ./terraform/data/ec2.pub
          overwrite: true
          retention-days: 1

  Terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: ec2.pub
          path: ./terraform/data/

      - name: Create env vars
        run: |
          echo AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID  }}" >> $GITHUB_ENV
          echo AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY  }}" >> $GITHUB_ENV

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.8.0"

      - name: Terraform init
        id: init
        run: |
          terraform \
          -chdir=./terraform \
          init \
          -backend-config="bucket=${{ vars.BACKEND_CONFIG_BUCKET  }}" \
          -backend-config="key=${{ vars.BACKEND_CONFIG_KEY  }}" \
          -backend-config="region=${{ vars.BACKEND_CONFIG_REGION  }}" \
          -backend-config="dynamodb_table=${{ vars.BACKEND_CONFIG_DYNAMODB_TABLE  }}"

      - name: Teraform destroy
        id: destroy
        run: |
          terraform \
          -chdir=./terraform \
          destroy \
          --auto-approve
